version: '3.7'
volumes:
  loki-storage:

x-log-options:
  &log-options
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"

services:
  loki:
    image: grafana/loki:1.5.0
    <<: *log-options
    container_name: "loki"
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - loki-storage:/loki
    command: -config.file=/etc/loki/local-config.yaml

networks:
  default:
    external:
      name: ocs-net
