version: '3.7'
volumes:
  grafana-storage:

networks:
  default:
    external:
      name: ocs-net

x-log-options:
  &log-options
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"

services:

  ocs-queen:
    image: queen_agent
    <<: *log-options
    hostname: gamow-docker
    environment:
      - INSTANCE_ID=queenagent
    volumes:
      - ~/primecam_readout/cfg:/cfg #outside:inside

  # grafana:
  #   image: queen_agent
  #   <<: *log-options
  #   restart: always
  #   ports:
  #     - "127.0.0.1:3000:3000"
  #     - "3000:3000"
  #   environment:
  #       - GF_RENDERING_SERVER_URL=http://grafana-renderer:8081/render
  #       - GF_RENDERING_CALLBACK_URL=http://grafana:3000
  #   volumes:
  #     - grafana-storage:/var/lib/grafana
  # grafana-renderer:
  #   <<: *log-options
  #   image: grafana/grafana-image-renderer:latest
  #   restart: always
