version: '3.7'

x-log-options:
  &log-options
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"

services:

  ocs-queen:
    image: queen_agent
    <<: *log-options
    hostname: gamow-docker
    network_mode: "host"
    environment:
      - INSTANCE_ID=queenagent
      - SITE_HUB=ws://127.0.0.1:8001/ws
      - SITE_HTTP=http://127.0.0.1:8001/call
    volumes: #outside:inside
      - /home/player1/ocs-site-configs/:/config       # OCS config files
      - /home/player1/primecam_readout/cfg:/cfg       # primecam_readout config
      - /home/player1/primecam_readout/logs:/logs     # primecam_readout logs
      - /home/player1/primecam_readout/drones:/drones # primecam_readout drones