version: '3.7'
networks:
  default:
    external:
      name: ocs-net

x-log-options:
  &log-options
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"

services:
  # --------------------------------------------------------------------------
  # OCS Core
  # --------------------------------------------------------------------------
  crossbar:
    image: simonsobs/ocs-crossbar:v0.10.1
    <<: *log-options
    restart: always
    ports:
      - "8001:8001"
    environment:
         - PYTHONUNBUFFERED=1
