version: '3.7'
networks:
  default:
    external:
      name: ocs-net

x-log-options:
  &log-options
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"

services:
  influxdb:
    image: "influxdb:1.7"
    <<: *log-options
    container_name: "influxdb"
    restart: always
    environment:
      - INFLUXDB_HTTP_LOG_ENABLED=false
    ports:
      - "8086:8086"
    volumes:
      - /srv/influxdb:/var/lib/influxdb
