version: '3.7'
networks:
  default:
    external:
      name: ocs-net

volumes:
  database-storage:
    external: true

x-log-options:
  &log-options
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"

x-ocs-base: &ocs-base
    hostname: gamow-docker
    user: ocs:ocs
    environment:
      LOGLEVEL: info
    volumes:
      - ${OCS_CONFIG_DIR}:/config
      - /data/:/data/

services:
  # --------------------------------------------------------------------------
  # OCS Core
  # --------------------------------------------------------------------------
  ocs-influxdb-publisher:
    image: simonsobs/ocs:${OCS_TAG}
    <<: *log-options
    hostname: gamow-docker
    environment:
      - INSTANCE_ID=influxagent
    volumes:
      - ${OCS_CONFIG_DIR}:/config:ro

  ocs-registry:
    image: simonsobs/ocs:${OCS_TAG}
    <<: *log-options
    container_name: ocs-registry
    hostname: gamow-docker
    environment:
      - INSTANCE_ID=registry
    volumes:
      - ${OCS_CONFIG_DIR}:/config:ro

  ocs-aggregator:
    image: simonsobs/ocs:${OCS_TAG}
    <<: *log-options
    container_name: ocs-aggregator
    hostname: gamow-docker
    user: "9000"
    environment:
      - LOGLEVEL=info
      - INSTANCE_ID=aggregator
    volumes:
      - ${OCS_CONFIG_DIR}:/config:ro
      - "/data/hk/:/data/"

  # --------------------------------------------------------------------------
  # SOCS Agents
  # --------------------------------------------------------------------------
  ocs-LSA23DG:
    image: simonsobs/socs:${SOCS_TAG}
    <<: *log-options
    hostname: gamow-docker
    network_mode: "host"
    environment:
      - INSTANCE_ID=LSA23DG
      - SITE_HUB=ws://127.0.0.1:8001/ws
      - SITE_HTTP=http://127.0.0.1:8001/call
    volumes:
      - ${OCS_CONFIG_DIR}:/config:ro

  ocs-370A7E:
    image: simonsobs/socs:${SOCS_TAG}
    <<: *log-options
    hostname: gamow-docker
    environment:
      - INSTANCE_ID=370A7E
    volumes:
      - ${OCS_CONFIG_DIR}:/config:ro
    devices:
      - "/dev/ttyUSBA7E:/dev/ttyUSBA7E"

  ocs-LSA280H:
    image: simonsobs/socs:${SOCS_TAG}
    <<: *log-options
    hostname: gamow-docker
    network_mode: "host"
    environment:
      - INSTANCE_ID=LSA280H
      - SITE_HUB=ws://127.0.0.1:8001/ws
      - SITE_HTTP=http://127.0.0.1:8001/call
    volumes:
      - ${OCS_CONFIG_DIR}:/config:ro

  ocs-psuBKP9130B:
    image: simonsobs/socs:${SOCS_TAG}
    hostname: gamow-docker
    network_mode: host
    environment:
      - INSTANCE_ID=psuBKP9130B
    volumes:
      - ${OCS_CONFIG_DIR}:/config:ro

  ocs-bluefors:
    image: simonsobs/socs:${SOCS_TAG}
    <<: *log-options
    hostname: gamow-docker
    volumes:
      - ${OCS_CONFIG_DIR}:/config:ro
      - /mnt/cosmo/bluefors/log/:/logs:ro
    environment:
      INSTANCE_ID: bluefors
      LOGLEVEL: "info"
      FRAME_LENGTH: 600
      STALE_TIME: 2
      MODE: "poll"

  # ---------------------------------------------------
  # ocs-util
  # ---------------------------------------------------
  ocs-util:
    image: simonsobs/ocs-util:${OCS_TAG}
    <<: *log-options
    container_name: ocs-util
    ports:
      - "127.0.0.1:8880:8880"
    environment:
      JUPYTER_PORT: 8880
      JUPYTER_PW: password
    volumes:
      - ${OCS_CONFIG_DIR}:/config
      - /data:/data

  ocs-teledyne:
    image: teledyne-test
    <<: *log-options
    hostname: gamow-docker
    network_mode: 'host'
    environment:
      - INSTANCE_ID=Tele1
      - SITE_HUB=ws://127.0.0.1:8001/ws
      - SITE_HTTP=http://127.0.0.1:8001/call
    volumes:
      - ${OCS_CONFIG_DIR}:/config:ro
    devices:
      - "/dev/ttyACM1:/dev/ttyACM1"

