name: Update Git Version

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - '**' # Match all branches

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the current Git version
        id: git_version
        run: echo "version=$(git describe --tags --always --dirty)" >> $GITHUB_ENV

      - name: Write version to file
        run: echo "${{ env.version }}" > VERSION

      - name: Commit and push updated version file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add VERSION
          git commit -m "Update version to ${{ env.version }}"
          git push origin ${{ github.ref }}
        # Prevent errors if there are no changes
        continue-on-error: true

